source 'sso://cpdc-internal/firebase'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '14.0'

target 'FirebaseUISample' do
  use_frameworks!
  platform :ios, '14.0'

  pod 'OCMock'
  pod 'FirebaseUI', :path => '../'

  target 'FirebaseUISampleUITests' do
    inherit! :search_paths
  end
end
